name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v4 # Adds a step to checkout the repository code

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
        cache-dependency-path: "DotnetTemplate.Web"
    
    - name: Restore .NET dependencies
      run: dotnet restore
    - name: Setup Node Dependencies
      working-directory: DotnetTemplate.Web
      run: npm ci

    - name: Build .NET
      run: dotnet build --no-restore

    - name: Test .NET
      run: dotnet test --no-build --verbosity normal
    - name: Test Node
      working-directory: DotnetTemplate.Web
      run: npm t
    - name: Lint Node
      working-directory: DotnetTemplate.Web
      run: npm run lint
